### ISSUE TITLE
TranslatableUpdateView doesn't work

### ISSUE THREAD

**Issue by mrgix** [django-parler/django-parler#145]
I've defined the translated field in the fileds property from the normal UpdateView but the method is extending: TranslatableUpdateView or TranslatableModelFormMixin, UpdateView

This is giving the error: Calling modelform_factory without defining 'fields' or 'exclude' explicitly is prohibited.

Can you fix this or show a update example in the examples?

**Comment by mrgix** [comment]
Possible Fix:

`                if self.fields:
                    fields = self.fields
                return modelform_factory(model, form=TranslatableModelForm, fields=fields)`

In views.py get_from_class(self) on line 294

**Comment by vdboor** [comment]
This is a confusing Django error, the real issue is typically that the `form_class` is not defined. Without such class, an attempt is made to construct one, and that fails when `fields` are not defined either.

We'll have to update the example indeed, creating a pull request (that adds a `form_class`) is welcome too!

**Comment by mrgix** [comment]
Pull request is ready for merging

**Comment by vdboor** [comment]
Merged! :-)
