### ISSUE TITLE
Little mistake (or perhaps a private joke)

### ISSUE THREAD

**Issue by TeddyBear06** [django-parler/django-parler#180]
Hi there :-)

First, thank you for your wonderful work!

_Easily translate "cheese omelet" into "omelette du fromage"._ **has to be** _Easily translate "cheese omelet" into "omelette **au** fromage"._  (inside the repository description).

Cheers or Cheese :-)

**Comment by vdboor** [comment]
Yes, this is a practical joke. The English version of Dexter's laboratory had this spelling incorrect. It turns out that the French version did fix that.

Maybe it's a bit overdue, and we can remove it. Should we?

https://www.google.nl/search?q=%22omelette+du+fromage%22 😄
http://django-parler.readthedocs.org/en/latest/background.html#package-naming

cc'ing the bugs: #17, #42, #59, #97, #101

**Comment by TeddyBear06** [comment]
Ahhh I see :-) Thanks for taking time to respond again (I didn't see the previous issues).

Keep it like this ;-) The English version of this episode is too funny !
