### ISSUE TITLE
Handling of ManyToMany fields is... missing?

### ISSUE THREAD

**Issue by egasimus** [django-parler/django-parler#5]
Hey everyone.

I got a M2M field included in TranslatedFields to show up fairly easily on the shared model, by adding a call to `cls._meta.get_m2m_with_model()` in a couple of places. However, now I'm getting this error:

```
"<CardTranslation: #None, cy, master: #None>" needs to have a value for field
    "cardtranslation" before this many-to-many relationship can be used.
```

I kind of have an idea why this is happening and was considering taking it upon myself to implementing M2M support (depends whether my current project will end up needing it, I guess). I wanted to hear your thoughts on this first, though. I've only started reading the Parler code today -- maybe someone more experienced could share a few caveats?

**Comment by vstoykov** [comment]
@egasimus Without traceback almost always is harder to tell why some error is raised. 

I saw your error when preparing a patch for #131. I'm not sure if this error is raised for you at the same place where it was raised for me (In the `TranslatedFieldsModel._get_field_values()` when running under Django 1.8). You can test my changes in #132 to see if it will work for you.

In order to fully support M2M fields in django-parler I think that more work need to be done, but probably my changes are the beginning.

**Comment by hedleyroos** [comment]
Thread necromancy. I added M2M support in https://github.com/django-parler/django-parler/pull/300.

**Comment by vdboor** [comment]
PR is merged!
