### ISSUE TITLE
Create form class to enter all languages at once.

### ISSUE THREAD

**Issue by bashu** [django-parler/django-parler#74]
This might be going a bit far, but would it be possible to switch between the languages without reloading the page? Ideally it would be nice for the user to be able to edit any of the different languages and hit "Save" and have them all save at once.

What do you think? Is this possible? Or very difficult?

**Comment by vdboor** [comment]
Well, the models can handle it for sure. I'm just not sure if that can be done in the adminm but it's worth a try!

I've wanted this to work in standard Django forms for some time now, because the parler-oscar integration does suffer from exposing just one language in the form. Having a form class that can generate fields for all languages would be a first good start to implement this!

**Comment by svezina** [comment]
+1
Having only one language at once with the form class can cause problems.  It would be nice if the form class automatically showed all languages. "Description (EN), Description (FR), etc.".

I find myself programming manual forms everytime there's a multilingual component.

**Comment by svezina** [comment]
Here is how I do my forms it in the meantime.

```
from parler.forms import TranslatableModelForm, TranslatedField
from django.utils.translation import gettext_lazy as _
from django.conf import settings

class MyForm(TranslatableModelForm):

    #add all multilingual fields to the form
    def __init__(self, *args, **kwargs):
        super(MyForm, self).__init__(*args, **kwargs)
        for lang_code, lang_name in settings.LANGUAGES:
            #I have no clue why this doesn't work without the try/except.
            try:
                self.instance.set_current_language(lang_code)
                self.fields["name_"+lang_code] = forms.CharField(label=_("Name ")+" ("+lang_code+")", max_length=100, required=True, initial=self.instance.name)
            except:
                self.instance.set_current_language(lang_code)

    #Save all multilingual fields
    def save(self, commit=True):
        instance = super(MyForm, self).save(commit=False)
        instance.save()
        for lang_code, lang_name in settings.LANGUAGES:
            instance.set_current_language(lang_code)
            instance.name = self.cleaned_data['name_'+lang_code]
            instance.save()
        return instance

    class Meta:
        model = MyModel
        fields = '__all__'
        exclude = ("name", "description",) #exclude multilingual fields because they are dealt with above

```

**Comment by vstoykov** [comment]
@svezina what is the exception that you are catching? Probably by knowing what is the exception someone can understand why happens.

**Comment by slomo** [comment]
I think the issue here is getting values from the translated instance for the initial data. That will fail upon creation and if a field is not set yet in the model.  At least that is what I have with django 1.8 and parler 1.6.4

"""
mymodel does not have a translation for the current language!
MyModel ID #5, language=de (tried fallbacks en)
Attempted to read attribute title.
"""

**Comment by MichelGhaith** [comment]
I am facing this problem too, I have model fields which the default fallback language is English.
And News model when i try to add new news instance i have to save the english first then add arabic language.
and the mobile user which preferred_language is arabic get a very bad experience

**Comment by svezina** [comment]
@MichelGhaith  10 years later, here is what I use.
Below is an example for a model, i define a multilingual_fields list in the top with all the settings. I define custom fields normally above, and add other unilingual fields in the META, as shown below.

```
class BookForm (forms.ModelForm):

    my_custom_field = forms.CharField()

    multilingual_fields = [
        {
            'name': 'title',
            'type': "forms.CharField(max_length=512)",
            'label': _("Title"),
            'style': '',
            'required': False,
            'classes': "form-control"
        },
        {
            'name': 'description',
            'type': "forms.CharField(widget=forms.Textarea)",
            'label': _("Description"),
            'rows': '2',
            'style': '',
            'required': False,
            'classes': "form-control"
        },
    ]

    def __init__(self, *args, **kwargs):
        super(BookForm,  self).__init__(*args, **kwargs)

        #detail with multilingual fields defined above
        for lang_code, lang_name in settings.LANGUAGES:
            for field in self.multilingual_fields:
                field_name = field['name'] + "_" + lang_code
                self.fields[field_name] = eval(field['type'])
                self.fields[field_name].label = field['label'] + " (" + lang_code + ")"
                self.fields[field_name].widget.attrs['class'] = field['classes']
                self.fields[field_name].widget.attrs['style'] = field['style']
                self.fields[field_name].required = field['required']
                if 'rows' in field:
                    self.fields[field_name].widget.attrs['rows'] = field['rows']
                if self.instance:
                    self.fields[field_name].initial = self.instance.safe_translation_getter(field['name'], language_code=lang_code)

        #other model fields (from META)
        self.fields['isbn'].required = True
        self.fields['isbn'].widget.attrs['class'] = "form-control"
        self.fields['isbn'].label = str(_("ISBN"))
        
        #other custom fields added above
        self.fields['my_custom_field'].required = True
        self.fields['my_custom_field'].widget.attrs['class'] = "form-control"
        self.fields['my_custom_field'].label = str(_("My custom field"))


    # Save all multilingual fields
    def save(self, commit=True):
        instance = super(BookForm, self).save(commit=False)
        for lang_code, lang_name in settings.LANGUAGES:
            for field in self.multilingual_fields:
                instance.set_current_language(lang_code)
                setattr(instance, field['name'], self.cleaned_data[field['name'] + '_' + lang_code])
        instance.save()
        return instance

    class Meta:
        model = Book
        fields = ['isbn']

```

When I have to create entries manually and only have 1 language, I make sure to loop over my languages to make sure I don't have empty languages, like this:

```
#unilingual field
isbn = "12345"

#multilingual fields:
title = "Multilingual frustrations 2nd edition"
description = "<p>Description...</p>"

book = Book()
book.isbn = isbn
#these two will only set in the current language, but it doesnt matter because i uglily add it again later.
book.title = title 
book.description = description
book.save()
for lang_code, lang_name in settings.LANGUAGES:
    book.set_current_language(lang_code)
    book.title = title
    book.description = description
    book.save()
```

It's a bit ugly but it works. There are surely better ways.
That said, I'm unfortunately slowly phasing out my use of django-parler since it seems abandonned, and I am planning a script to convert and move to django-modeltranslation, which supports Django 5 better, has better performance because it doesnt use a second table for translations, and needs much less hacks like this.  Note that django-modeltranslation will also need a hacky form to add all languages in the same form, but the logic of my example form above can be used with very little modifications.
